### PR TITLE
Bugfix/bullet resist lvl scaling

### PR DESCRIPTION
**Pull request by Surxe**
Addresses #79 

BulletResist scaling was being considered a separate stat to base BulletResist, and was giving misleading info on deadlocked.wiki/Hero Comparison. This simply merges the stats.

Opposite to the proposal in the issue, I changed BulletArmorDamageReduction to BulletResist via hero attribute remap, rather than remapping BulletResist level scaling to BulletArmorDamageReduction.

Did the same for TechArmorDamageReduction to TechResist.

Uploaded hero and attribute data and confirmed its correct on deadlocked.wiki/Hero Comparison.

### CODE REVIEW

**Review by B13rg — APPROVED** [review]

**Comment by Surxe** [comment]
I presume you wish to merge in the previous 2 minor patches before this gets merged?

**Review by hassayag — CHANGES_REQUESTED** [review]
`BonusAttackRange` also has no base value of the same name. Does that also need a fix?

**Comment by Surxe** [comment]
> `BonusAttackRange` also has no base value of the same name. Does that also need a fix?

Bebop scales attack range so its included. The get_meaningful_stats includes any stats that are scaled

**Comment by hassayag** [comment]
> > `BonusAttackRange` also has no base value of the same name. Does that also need a fix?
> 
> Bebop scales attack range so its included. The get_meaningful_stats includes any stats that are scaled

Sure, but if you look at Bebop's hero data, there is no base value for `BonusAttackRange`. So isn't that the same issue as what you have with `BulletResist`?

**Comment by Surxe** [comment]
> > > `BonusAttackRange` also has no base value of the same name. Does that also need a fix?
> > 
> > 
> > Bebop scales attack range so its included. The get_meaningful_stats includes any stats that are scaled
> 
> Sure, but if you look at Bebop's hero data, there is no base value for `BonusAttackRange`. So isn't that the same issue as what you have with `BulletResist`?

Ah I see. Luckily that's not an issue:
image

Its only an issue if the base stat doesnt match the scaling stat. There can be a scaling stat without a base stat, and vice versa.

**Review by hassayag — APPROVED** [review]
Sweet, off it can go 🚀

**Comment by Surxe** [comment]
@hassayag Do you want to merge in the last 2 patches with a separate PR, or fine to merge them in with this?

**Comment by hassayag** [comment]
> @hassayag Do you want to merge in the last 2 patches with a separate PR, or fine to merge them in with this?

Oh there was a patch yesterday, that's the only missing one i think. Let me merge that into develop myself first to keep the commit history clean

**Pull request merged**
