### PR TITLE
Feature/pull game files from s3

### PR DESCRIPTION
**Pull request by hassayag**
- **Created `DataTransfer` class to handle read/write of the S3 bucket**
  - `S3` class is now more general purpose
- Fixed directory of data uploaded to S3
- New `import_file` arg to trigger import at the beginning of deadbot process
- New `build_num` arg to select version to import. Default will get the latest version

### CODE REVIEW

**Review by Surxe — COMMENTED** [review]
Did a very light skim and it looks good, though its well out of my wheelhouse so trust yourself to self-review and self-approve this one

**Review by B13rg — CHANGES_REQUESTED** [review]
I like how each version has it's own folder; good defaults too

Be sure to add shutil to the poetry config with `poetry add shutil` as well

Looks really good, that's all that's needed to me!

**Comment by hassayag** [comment]
> Be sure to add shutil to the poetry config with `poetry add shutil` as well

I didn't need to install shutil as it looks like its just a part of python by default

**Review by B13rg — APPROVED** [review]

**Comment by B13rg** [comment]
Looks great!  Nice job!

**Pull request merged**
